name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: bld

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
           sudo apt-get install -y libprotoc-dev protobuf-compiler libgoogle-glog-dev cmake libgtest-dev
           cd /usr/src/gtest && sudo env "PATH=$PATH" cmake . && sudo make -j $(nproc) && sudo mv lib/libgtest* /usr/lib/ && cd -

    - name: Build our project
      run: |
           make -j $(nproc)

    - name: Run tests
      run: |
          test/test_common
          test/test_dict
