name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_DIR: bld

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install protobuf and gtest
      run: |
           sudo apt install libprotoc-dev
           sudo apt install protobuf-compiler
           sudo apt install -y cmake libgtest-dev && cd /usr/src/gtest && sudo env  env "PATH=$PATH" cmake . && sudo make -j $(nproc) && sudo mv libgtest* /usr/lib/ && cd -

    - name: Build our project
      run: |
           make -j $(nproc)

    - name: Run tests
      run: |
          output/test/test_common
          output/test/test_dict
